name       : budgie-control-center
version    : 1.1.0
release    : 9
source     :
    - https://github.com/BuddiesOfBudgie/budgie-control-center/releases/download/v1.1.0/budgie-control-center-1.1.0.tar.xz : 1d0de48749c10e43f1e66b3a95557118cbd6815b659c4881f040d324dc7a8abc
license    : GPL-2.0-or-later
component  : desktop.budgie
summary    : Budgie Control Center is a fork of GNOME Control Center for the Budgie 10 Series
description: |
    Budgie Control Center is a fork of GNOME Settings / GNOME Control Center with the intent of providing a simplified list of settings that are applicable to the Budgie 10 series, along with any small quality-of-life settings.
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(colord-gtk)
    - pkgconfig(com_err)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(ibus-1.0)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-bluetooth-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-settings-daemon)
    - pkgconfig(goa-backend-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(gsound)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgnome-menu-3.0)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(libpulse-mainloop-glib)
    - pkgconfig(libsecret-1)
    - pkgconfig(libwacom)
    - pkgconfig(ModemManager)
    - pkgconfig(pwquality)
    - pkgconfig(smbclient)
    - pkgconfig(udisks2)
    - pkgconfig(upower-glib)
    - bluez
    - cups-devel
    - docbook-xml
    - gnome-common
    - kerberos-devel
    - libnma-devel
rundeps    :
    - bolt # Thunderbolt support
    - cups-pk-helper
    - glib-networking
    - gnome-color-manager
    - gnome-keyring
    - gvfs-goa
    - libgnomekbd
    - power-profiles-daemon
    - sound-theme-freedesktop
networking : yes
setup      : |
    %meson_configure -Dcheese=false -Ddocumentation=true -Dprivileged_group=sudo
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Consistent polkit rules naming
    mv $installdir/usr/share/polkit-1/rules.d/budgie-control-center.rules $installdir/usr/share/polkit-1/rules.d/org.buddiesofbudgie.controlcenter.rules
